name: Units Tests

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Python 3.x
      uses: actions/setup-python@v3
      with:
        python-version: 3.x
        architecture: x64

    - name: Install Poetry
      run: pipx install poetry

    - name: Install dependencies
      run: poetry install

    - name: Run Tests
      run: poetry run pytest tests/

    - name: Run Linter
      run: poetry run flake8 src/
